#!/bin/bash

# create symlinks to directories on the volume
for f in {diag,admin,fast_recovery_area,oradata} product/11.2.0/xe/{dbs,log,config/log,network/admin}
do rm -rf /u01/app/oracle/$f && ln -s /oracle/${f//\//_} /u01/app/oracle/$f
done

# Update HOST with actual value, uniquely generated by Docker on each start
sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g" $ORACLE_HOME/network/admin/listener.ora
sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g" $ORACLE_HOME/network/admin/tnsnames.ora

/etc/init.d/oracle-xe start || ( echo 'Cannot startup Oracle XE' ; exit 1 )
trap "/etc/init.d/oracle-xe stop ; END=1" INT TERM

while [ "$END" == '' ]; do sleep 1; done

